// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-2jwJEzkLg8SgFZ4ko6ED49lvh174Pv4',
    appId: '1:713260913456:web:a917bd908230e66d10eef5',
    messagingSenderId: '713260913456',
    projectId: 'saafhisaab-dd3ca',
    authDomain: 'saafhisaab-dd3ca.firebaseapp.com',
    storageBucket: 'saafhisaab-dd3ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB93o7o8ct6LEy7d5dAKSBv8mZo5f11nGI',
    appId: '1:713260913456:android:5951dfa0e1dd37f710eef5',
    messagingSenderId: '713260913456',
    projectId: 'saafhisaab-dd3ca',
    storageBucket: 'saafhisaab-dd3ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8HCSyEeumNYRpEpR4rw-f_zEYRe895_o',
    appId: '1:713260913456:ios:f3a0fc8cfa84ba3910eef5',
    messagingSenderId: '713260913456',
    projectId: 'saafhisaab-dd3ca',
    storageBucket: 'saafhisaab-dd3ca.firebasestorage.app',
    iosBundleId: 'com.example.saafhisaab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8HCSyEeumNYRpEpR4rw-f_zEYRe895_o',
    appId: '1:713260913456:ios:f3a0fc8cfa84ba3910eef5',
    messagingSenderId: '713260913456',
    projectId: 'saafhisaab-dd3ca',
    storageBucket: 'saafhisaab-dd3ca.firebasestorage.app',
    iosBundleId: 'com.example.saafhisaab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-2jwJEzkLg8SgFZ4ko6ED49lvh174Pv4',
    appId: '1:713260913456:web:1d3dcbef2f0ec11f10eef5',
    messagingSenderId: '713260913456',
    projectId: 'saafhisaab-dd3ca',
    authDomain: 'saafhisaab-dd3ca.firebaseapp.com',
    storageBucket: 'saafhisaab-dd3ca.firebasestorage.app',
  );
}
